version: '3.8'

services:
  # Flask Application
  sgmm-app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB_NAME=sgmm_db
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_API_KEY=
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-large}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
    command: gunicorn --bind 0.0.0.0:5000 --timeout 300 --workers 2 --worker-class sync run:app
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./books:/app/books
    depends_on:
      mongodb:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=
      - CLUSTER_HOSTNAME=node1
      - AUTHENTICATION_APIKEY_ENABLED=false
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS=
      - AUTHORIZATION_ADMINLIST_ENABLED=false
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # Initialize the database (runs once and exits)
  init-db:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB_NAME=sgmm_db
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_API_KEY=
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    command: python -m app.utils.init_db
    restart: on-failure

volumes:
  mongodb_data:
  weaviate_data: 