name: Deploy Node.js App to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Connect to Droplet & Deploy
        run: |
          sshpass -p "${{ secrets.DO_DROPLET_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_DROPLET_USER }}@${{ secrets.DO_DROPLET_IP }} <<EOF
            # Variables
            APP_DIR=/root/node-app
            DEPLOY_DIR=/root/sgmm-api

            # Clean up and clone latest
            rm -rf \$APP_DIR
            git clone https://github.com/unisphere-wiki/sgmm-front-end.git \$APP_DIR

            cd \$APP_DIR

            # Install and build
            npm install
            npm run build

            # Copy dist folder
            rm -rf \$DEPLOY_DIR/dist
            cp -r build \$DEPLOY_DIR/bizquery-dist

            echo "Deployment complete."
          EOF
