name: Build & Deploy Node.js App to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Remove old build from Droplet
        run: |
          sshpass -p "${{ secrets.DO_DROPLET_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_DROPLET_USER }}@${{ secrets.DO_DROPLET_IP }} "rm -rf /root/sgmm-api/bizquery"

      - name: Deploy build to Droplet
        run: |
          sshpass -p "${{ secrets.DO_DROPLET_PASSWORD }}" scp -o StrictHostKeyChecking=no -r build ${{ secrets.DO_DROPLET_USER }}@${{ secrets.DO_DROPLET_IP }}:/root/sgmm-api/bizquery
